# Generated by Django 3.1 on 2020-10-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20201006_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='نام ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='پست الکترونیکی')),
                ('body', models.TextField(null=True, verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ تغییر')),
                ('active', models.BooleanField(null=True, verbose_name='فعال')),
            ],
            options={
                'db_table': 'all_comment',
            },
        ),
        migrations.CreateModel(
            name='UniversityComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='نام ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='پست الکترونیکی')),
                ('body', models.TextField(null=True, verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ تغییر')),
                ('active', models.BooleanField(null=True, verbose_name='فعال')),
                ('University', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.university', verbose_name='نام دانشگاه ')),
            ],
            options={
                'db_table': 'university_comment',
            },
        ),
        migrations.CreateModel(
            name='ConsultantComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='نام ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='پست الکترونیکی')),
                ('body', models.TextField(null=True, verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ تغییر')),
                ('active', models.BooleanField(null=True, verbose_name='فعال')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='account.consultant', verbose_name='نام مشاور ')),
            ],
            options={
                'db_table': 'consultant_comment',
            },
        ),
    ]
