# Generated by Django 3.1 on 2020-10-04 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user', verbose_name='نام دانش آموز ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='درباره من ')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='لینک یکتا')),
                ('identity_code', models.CharField(max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('rate_exam', models.CharField(blank=True, max_length=40, null=True, verbose_name='رتبه کنکور')),
                ('show_rate', models.BooleanField(default=False, null=True, verbose_name=' نمایش رتبه کنکور')),
                ('interest_major', models.CharField(blank=True, max_length=60, null=True, verbose_name='رشته های مورد علاقه')),
                ('bachelor_average', models.FloatField(blank=True, null=True, verbose_name='معدل کارشناسی')),
                ('master_tendency', models.CharField(blank=True, max_length=50, null=True, verbose_name='گرایش ارشد')),
                ('phd_tendency', models.CharField(blank=True, max_length=50, null=True, verbose_name='گرایش دکتری ')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات')),
                ('consulting_type', models.CharField(blank=True, choices=[('CHAT', 'تماس متنی'), ('VOICE CALL', 'تماس صوتی'), ('VIDEO CALL', 'تماس تصویری'), ('ALL', 'هر نوع تماس'), ('CHAT_VOICE', 'متنی و صوتی'), ('CHAT_VIDEO', 'متنی و ویدیویی'), ('VOICE_VIDEO', 'صوتی و ویدیویی')], max_length=15, verbose_name='نوع مشاوره ')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultant',
            },
        ),
    ]
