# Generated by Django 3.1 on 2020-10-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_consultant_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, max_length=150, verbose_name='نام دانشگاه ')),
                ('university_city', models.CharField(blank=True, max_length=100, verbose_name='شهر دانشگاه ')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='لینک یکتا')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('website', models.URLField(null=True, verbose_name='آدرس وب سایت')),
                ('about_university', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='تصویر')),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(blank=True, max_length=100, verbose_name='نام رشته ')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='لینک یکتا')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img/major', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('university_major', models.ManyToManyField(blank=True, to='account.University', verbose_name='دانشگاه های شامل این رشته')),
            ],
            options={
                'db_table': 'major',
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='bachelor_major',
            field=models.ManyToManyField(blank=True, to='account.Major', verbose_name='رشته کارشناسی'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='universities',
            field=models.ManyToManyField(blank=True, to='account.University', verbose_name='دانشگاه محل تحصیل کارشناسی'),
        ),
    ]
