# Generated by Django 3.1 on 2020-10-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201004_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'verbose_name': 'مشاور', 'verbose_name_plural': 'مشاوران'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'دانش آموز', 'verbose_name_plural': 'دانش آموزان'},
        ),
    ]
